# Generated by Django 5.0.4 on 2026-04-01 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('step', models.CharField(choices=[('collecting_intent', 'Collecting Intent'), ('provider_selection', 'Provider Selection'), ('slot_selection', 'Slot Selection'), ('confirmation', 'Confirmation'), ('completed', 'Completed')], default='collecting_intent', max_length=32)),
                ('draft', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
