# Generated by Django 5.0.4 on 2026-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
