# Generated by Django 5.0.4 on 2026-04-01 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('GEN', 'General Practice'), ('CARD', 'Cardiology'), ('DERMA', 'Dermatology'), ('ENDO', 'Endocrinology'), ('GAST', 'Gastroenterology'), ('NEUR', 'Neurology'), ('PED', 'Pediatrics'), ('PSY', 'Psychiatry'), ('RAD', 'Radiology'), ('SURG', 'Surgery')], max_length=5),
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.providerprofile')),
            ],
            options={
                'unique_together': {('provider', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
