# Generated by Django 5.0.4 on 2026-04-01 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_providerprofile_specialty_provideravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='provideravailability',
            name='day',
        ),
    ]
