# Generated by Django 5.0.4 on 2026-04-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provideravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'date', 'start_time', 'end_time')},
        ),
    ]
